const $=s=>document.querySelector(s),cv=$('#game'),ctx=cv.getContext('2d');
const levels=[['A Estrada do Guardião','#23342d','#65796b'],['Ruínas de Cinza','#392725','#795448'],['Profundezas de Cristal','#18253c','#466a82'],['Capela Afogada','#1e292b','#526569'],['Bastião de Ferro','#302f2c','#71695c'],['Ponte da Lua','#151b31','#465574'],['Fortaleza Negra','#1b141f','#613945']];
let W,H,scene='menu',lv=0,paused=false,keys={},press={},cam=0,t=0,boss=null;
let S={hp:120,max:120,st:100,potions:2,coins:0,keys:0,crystals:0,x:100,y:250,vx:0,vy:0,on:false,face:1,atk:0,inv:0,checkpoint:100};
const enemies=[]; const items=[];
function resize(){W=cv.width=Math.max(720,innerWidth);H=cv.height=Math.max(405,innerHeight)} addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{if(!keys[e.code])press[e.code]=1;keys[e.code]=1;if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&scene==='game')togglePause()});addEventListener('keyup',e=>keys[e.code]=0);
function show(id){document.querySelectorAll('.screen').forEach(x=>x.classList.add('hidden'));$(id).classList.remove('hidden')}
function overlay(id,on=true){$(id).classList.toggle('hidden',!on);paused=on}
function save(){localStorage.setItem('tsm_web',JSON.stringify({lv,S}))} function load(){try{let d=JSON.parse(localStorage.getItem('tsm_web'));if(d){lv=d.lv;Object.assign(S,d.S);return true}}catch(e){}return false}
function setupLevel(i){lv=i;S.x=100;S.y=180;S.vx=S.vy=0;S.hp=S.max;S.st=100;S.checkpoint=100;cam=0;enemies.length=0;items.length=0;let len=3600+i*240;for(let x=620;x<len-300;x+=420+(i*17)%100)enemies.push({x,y:260,w:34,h:58,hp:40+i*8,vx:0,dead:false,type:(x/400|0)%4});for(let x=420;x<len-200;x+=620)items.push({x,y:220,type:(x/600|0)%4,taken:false});boss=i===6?{x:3050,y:210,w:70,h:108,hp:520,max:520}:null;let tt=$('#levelTitle');tt.querySelector('b').textContent=levels[i][0];tt.querySelector('span').textContent='Capítulo '+(i+1)+' de 7';tt.classList.add('show');setTimeout(()=>tt.classList.remove('show'),2200);$('.objective').innerHTML='<b>Objetivo</b> · '+(i===6?'Derrote Vharos':'Alcance o portão oriental');$('#bossHud').classList.add('hidden');save()}
function begin(i=0){scene='game';show('#gameScreen');setupLevel(i);paused=false;setTimeout(()=>dialog('Narrador',i===0?'A velha estrada ainda carrega as marcas do cerco. A coroa de Valdora foi quebrada e o reino ficou sem um guardião.':'Você entra em '+levels[i][0]+'. Cada passo leva mais perto da Coroa Quebrada.'),250)}
function dialog(name,text){paused=true;let d=$('#dialogue');d.querySelector('.speaker').textContent=name;d.querySelector('.line').textContent=text;d.classList.remove('hidden')}
function closeDialog(){let d=$('#dialogue');if(!d.classList.contains('hidden')){d.classList.add('hidden');paused=false;return true}return false}
addEventListener('keydown',e=>{if((e.code==='KeyE'||e.code==='Enter')&&scene==='game')closeDialog()});
function togglePause(){if(closeDialog())return;overlay('#pause',$('#pause').classList.contains('hidden'));updateHUD()}
function platforms(){let a=[[0,330,780,120],[840,305,460,145],[1360,338,390,112],[1810,292,520,158],[2390,325,520,125],[2970,285,900,165]];for(let k=0;k<6;k++)a.push([360+k*580,235-(k%2)*35,170,20]);return a}
function hitbox(a,b){return a.x<a.x+a.w&&a.x+a.w>b.x&&a.x<b.x+b.w&&a.y+a.h>b.y&&a.y<b.y+b.h}
function groundColl(o){o.on=false;for(const p of platforms()){let [x,y,w,h]=p;if(o.x+o.w>x&&o.x<x+w&&o.y+o.h>=y&&o.y+o.h<=y+18&&o.vy>=0){o.y=y-o.h;o.vy=0;o.on=true}}}
function hurtPlayer(d,from){if(S.inv>0)return;S.hp-=d;S.inv=45;S.vx=(S.x<from?-6:6);S.vy=-5;if(S.hp<=0){S.hp=0;paused=true;$('#death').classList.remove('hidden')}}
function attack(){let a={x:S.face>0?S.x+28:S.x-62,y:S.y+8,w:62,h:48};for(const e of enemies)if(!e.dead&&hitbox(a,e)){e.hp-=24;if(e.hp<=0){e.dead=true;S.coins+=8}}if(boss&&boss.hp>0&&hitbox(a,boss)){boss.hp-=20;if(boss.hp<=0){boss.hp=0;$('#bossHud').classList.add('hidden');dialog('Vharos','Então carregue a coroa... e descubra quanto ela pesa.')}}}
function update(){if(scene!=='game'||paused)return;t++;let sp=keys.KeyA||keys.ArrowLeft?-1:keys.KeyD||keys.ArrowRight?1:0;if(sp){S.vx+=sp*.65;S.face=sp}S.vx*=.82;S.vx=Math.max(-5.4,Math.min(5.4,S.vx));if((press.Space||press.KeyW||press.ArrowUp)&&S.on){S.vy=-10.5;S.on=false}if((press.KeyJ||press.KeyZ)&&S.atk<=0){S.atk=18;attack()}if((press.KeyK)&&S.st>=25){S.st-=25;S.vx=S.face*10;S.inv=14}if((press.ShiftLeft||press.ShiftRight)&&S.st>=18){S.st-=18;S.vx=S.face*12;S.inv=18}if(press.KeyH&&S.potions>0&&S.hp<S.max){S.potions--;S.hp=Math.min(S.max,S.hp+55)}S.st=Math.min(100,S.st+.35);S.vy+=.55;S.x+=S.vx;S.y+=S.vy;S.x=Math.max(0,S.x);groundColl({get x(){return S.x},set x(v){S.x=v},get y(){return S.y},set y(v){S.y=v},w:30,h:62,get vy(){return S.vy},set vy(v){S.vy=v},set on(v){S.on=v}});if(S.y>H+100){S.x=S.checkpoint;S.y=160;S.hp=Math.max(35,S.hp-20)}if(S.atk>0)S.atk--;if(S.inv>0)S.inv--;
for(const e of enemies){if(e.dead)continue;let dx=S.x-e.x;e.vx+=(Math.abs(dx)<280?Math.sign(dx)*.12:Math.sin(t/80+e.x)*.03);e.vx*=.9;e.x+=e.vx;if(Math.abs(dx)<38&&Math.abs(S.y-e.y)<70)hurtPlayer(8+lv*2,e.x)}
for(const it of items){if(it.taken)continue;if(Math.abs(S.x-it.x)<30&&Math.abs(S.y-it.y)<80){it.taken=true;if(it.type===0)S.coins+=10;if(it.type===1)S.potions++;if(it.type===2)S.keys++;if(it.type===3)S.crystals++}}
if(S.x>2050&&S.checkpoint<2050){S.checkpoint=2050;save()}
if(boss){if(S.x>2750&&boss.hp>0)$('#bossHud').classList.remove('hidden');if(boss.hp>0){let dx=S.x-boss.x;boss.x+=Math.sign(dx)*1.5;if(Math.abs(dx)<72)hurtPlayer(18,boss.x);$('#bossFill').style.width=(boss.hp/boss.max*100)+'%'}}
let end=3550+lv*240;if(!boss&&S.x>end){if(lv<6)setupLevel(lv+1)}cam+=(Math.max(0,S.x-W*.38)-cam)*.09;updateHUD();for(let k in press)delete press[k]}
function updateHUD(){$('#hpFill').style.width=S.hp/S.max*100+'%';$('#stFill').style.width=S.st+'%';$('#hpText').textContent=Math.ceil(S.hp)+'/'+S.max;$('#stText').textContent=Math.round(S.st);$('#potions').textContent=S.potions;$('#coins').textContent=S.coins;$('#keys').textContent=S.keys;$('#invPotion').textContent=S.potions;$('#invCrystal').textContent=S.crystals;$('#invKeys').textContent=S.keys;$('#pauseLoc').textContent=levels[lv][0]}
function draw(){if(scene!=='game')return;let [name,sky,fog]=levels[lv];let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,sky);g.addColorStop(1,'#08090b');ctx.fillStyle=g;ctx.fillRect(0,0,W,H);ctx.globalAlpha=.22;ctx.fillStyle=fog;for(let i=-1;i<9;i++){let x=i*220-(cam*.15%220);ctx.beginPath();ctx.ellipse(x,H*.62,230,52,0,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const p of platforms()){let [x,y,w,h]=p,dx=x-cam;ctx.fillStyle=lv===2?'#293d54':'#2f302f';ctx.fillRect(dx,y,w,h);ctx.fillStyle='rgba(255,255,255,.08)';ctx.fillRect(dx,y,w,2);for(let q=0;q<w;q+=38){ctx.fillStyle='rgba(0,0,0,.12)';ctx.fillRect(dx+q,y+6,2,h-6)}}for(const it of items){if(it.taken)continue;let x=it.x-cam,y=it.y+Math.sin(t/15+it.x)*4;ctx.fillStyle=['#d1aa57','#9d4d49','#a98c52','#70a4c4'][it.type];ctx.beginPath();ctx.arc(x,y,7,0,7);ctx.fill()}for(const e of enemies){if(e.dead)continue;let x=e.x-cam;ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(x+17,e.y+58,24,7,0,0,7);ctx.fill();ctx.fillStyle=['#57423e','#3f4146','#4d3634','#384651'][e.type];ctx.fillRect(x,e.y,34,58);ctx.fillStyle='#a16b55';ctx.beginPath();ctx.arc(x+17,e.y-2,10,0,7);ctx.fill();ctx.fillStyle='#c85d4d';ctx.fillRect(x+21,e.y-5,3,2)}if(boss&&boss.hp>0){let x=boss.x-cam;ctx.fillStyle='#252129';ctx.fillRect(x,boss.y,70,108);ctx.fillStyle='#7b6055';ctx.beginPath();ctx.arc(x+35,boss.y-8,16,0,7);ctx.fill();ctx.strokeStyle='#aaa';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(x+48,boss.y+20);ctx.lineTo(x+92,boss.y+48);ctx.stroke()}let px=S.x-cam;ctx.save();ctx.globalAlpha=S.inv>0&&t%4<2?.45:1;ctx.fillStyle='rgba(0,0,0,.45)';ctx.beginPath();ctx.ellipse(px+15,S.y+64,24,7,0,0,7);ctx.fill();ctx.fillStyle='#383e46';ctx.fillRect(px,S.y+18,30,44);ctx.fillStyle='#9e8068';ctx.beginPath();ctx.arc(px+15,S.y+8,11,0,7);ctx.fill();ctx.strokeStyle='#c4c6c5';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(px+(S.face>0?25:5),S.y+25);ctx.lineTo(px+(S.face>0?65:-35),S.y+(S.atk?8:35));ctx.stroke();ctx.restore();}
function loop(){update();draw();requestAnimationFrame(loop)}requestAnimationFrame(loop);
function chapters(){let c=$('#chapterList');c.innerHTML='';levels.forEach((l,i)=>{let b=document.createElement('button');b.className='menu-btn';b.style.width='100%';b.textContent=(i+1).toString().padStart(2,'0')+' · '+l[0];b.onclick=()=>{overlay('#chapters',false);begin(i)};c.appendChild(b)})}chapters();
$('#newGame').onclick=()=>{S={hp:120,max:120,st:100,potions:2,coins:0,keys:0,crystals:0,x:100,y:250,vx:0,vy:0,on:false,face:1,atk:0,inv:0,checkpoint:100};begin(0)};$('#continueGame').onclick=()=>{load();begin(lv)};$('#controlsBtn').onclick=()=>overlay('#controls');$('#optionsBtn').onclick=()=>overlay('#options');$('#chapterBtn').onclick=()=>overlay('#chapters');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>overlay('#'+b.dataset.close,false));$('#resume').onclick=()=>overlay('#pause',false);$('#toMenu').onclick=()=>{overlay('#pause',false);scene='menu';show('#mainMenu')};$('#respawn').onclick=()=>{$('#death').classList.add('hidden');paused=false;S.hp=S.max;S.x=S.checkpoint;S.y=160};$('#grainToggle').oninput=e=>$('#grain').style.opacity=e.target.value/100;let has=load();$('#continueGame').disabled=!has;$('#continueGame').style.opacity=has?1:.45;$('#loading').classList.add('hidden');show('#mainMenu');updateHUD();