(()=>{
'use strict';
const $=s=>document.querySelector(s),cv=$('#game'),ctx=cv.getContext('2d');
let W=1280,H=720,DPR=1,scene='menu',paused=false,keys={},pressed={},time=0,last=0,cam=0,shake=0,areaMode='world';
const LEVELS=[
{name:'Estrada do Guardião',sub:'Fronteira de Valdora',len:3900,sky:['#263a3a','#6b675d'],ground:'#302d28',accent:'#7f8d70',quest:'Encontre o Selo do Guardião e abra o portão oriental.'},
{name:'Ruínas de Cinza',sub:'Distrito queimado',len:4300,sky:['#43312e','#82604e'],ground:'#352b27',accent:'#a1664d',quest:'Atravesse as ruínas e encontre a passagem sob a torre caída.'},
{name:'Profundezas de Cristal',sub:'Minas de Nareth',len:4500,sky:['#16253a','#3c5877'],ground:'#222936',accent:'#7196b1',quest:'Desça até a galeria antiga e atravesse o veio lunar.'},
{name:'Capela Afogada',sub:'Santuário submerso',len:4400,sky:['#23353a','#49646a'],ground:'#293234',accent:'#6f9996',quest:'Reative os três altares e alcance a nave superior.'},
{name:'Bastião de Ferro',sub:'Forja real',len:5000,sky:['#353535','#6b645a'],ground:'#302f2e',accent:'#9b7450',quest:'Sabote a forja antes que o portão interno se feche.'},
{name:'Ponte da Lua',sub:'Travessia dos reis',len:4700,sky:['#1b2339','#4b5877'],ground:'#292a31',accent:'#8593b3',quest:'Cruze a ponte durante a tempestade e sobreviva aos sentinelas.'},
{name:'Fortaleza Negra',sub:'Trono de Vharos',len:4200,sky:['#221923','#643744'],ground:'#292329',accent:'#a24f5b',quest:'Chegue ao salão da coroa e derrote Vharos.'}
];
const DIALOGS=[
['Edrin','O portão oriental foi selado quando a guarda caiu. O Selo do Guardião ainda está na gruta sob o velho carvalho. Sem ele, ninguém passa.'],
['Narrador','Cinzas cobrem as ruas. Algumas portas ainda estão quentes.'],
['Narrador','Os cristais vibram quando Kael se aproxima, como se lembrassem de sua espada.'],
['Narrador','A água tomou o santuário, mas três sinos continuam tocando sob a superfície.'],
['Narrador','O Bastião trabalha sem descanso. Martelos caem mesmo onde já não existem ferreiros vivos.'],
['Narrador','A ponte some dentro das nuvens. Lá embaixo, nada além de trovões.'],
['Vharos','Você atravessou um reino morto para encontrar um homem que já venceu. Venha, então. Mostre-me o peso da sua espada.']
];
let state={hp:140,maxHp:140,st:100,potions:3,marks:0,keys:0,crystals:0,level:0,checkpoint:110,hasSigil:false,caveSeen:false,gateOpen:false,save:false};
let player=null,enemies=[],projectiles=[],particles=[],props=[],boss=null,npc=null,gate=null,caveDoor=null,checkpoint=null,secret=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),lerp=(a,b,t)=>a+(b-a)*t;
function rnd(n){let x=Math.sin(n*12.9898+78.233)*43758.5453;return x-Math.floor(x)}
function resize(){DPR=Math.min(2,devicePixelRatio||1);W=innerWidth;H=innerHeight;cv.width=W*DPR;cv.height=H*DPR;cv.style.width=W+'px';cv.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0)}
addEventListener('resize',resize);resize();
addEventListener('keydown',e=>{if(!keys[e.code])pressed[e.code]=1;keys[e.code]=1;if(['Space','ArrowUp','ArrowDown'].includes(e.code))e.preventDefault();if(e.code==='Escape'&&scene==='game')togglePause()});
addEventListener('keyup',e=>keys[e.code]=0);
function save(){state.save=true;state.level=state.level|0;localStorage.setItem('tsm_v3',JSON.stringify(state))}
function load(){try{Object.assign(state,JSON.parse(localStorage.getItem('tsm_v3'))||{})}catch(e){}}
function show(id,v=true){$(id).classList.toggle('hidden',!v)}
function enterGame(){scene='game';show('#menu',false);show('#play',true)}
function openDialog(speaker,line){paused=true;$('#speaker').textContent=speaker;$('#dialogLine').textContent=line;show('#dialog',true)}
function closeDialog(){if(!$('#dialog').classList.contains('hidden')){show('#dialog',false);paused=false;return true}return false}
function groundAt(x,level=state.level){let base=H-120;let a=Math.sin(x*.0037+level)*10,b=Math.sin(x*.011+2.1)*4;return base+a+b}
function caveGround(x){return H-105+Math.sin(x*.012)*3}
function newPlayer(x){return{x,y:groundAt(x)-94,vx:0,vy:0,w:38,h:88,face:1,onGround:true,atk:0,heavy:0,dodge:0,ifr:0,guard:0,parry:0,hurt:0,anim:0,combo:0,comboT:0}}
function makeEnemy(x,type=0,elite=false){return{x,y:groundAt(x)-82,vx:0,vy:0,w:type===1?52:40,h:type===1?54:82,hp:(type===0?60:type===1?48:type===2?45:70)*(elite?1.6:1),max:0,type,elite,face:-1,state:'patrol',timer:40+rnd(x)*80,home:x,dead:false,ifr:0,attackBox:null};}
function buildLevel(i,spawn=110){state.level=i;areaMode='world';let L=LEVELS[i];player=newPlayer(spawn);cam=clamp(spawn-W*.32,0,L.len-W);enemies=[];particles=[];projectiles=[];props=[];boss=null;state.checkpoint=spawn;
for(let n=0;n<11+i;n++){let x=520+n*((L.len-900)/(10+i));let type=(n+i)%4;enemies.push(makeEnemy(x,type,n%6===5))}
for(let n=0;n<32;n++){let x=90+n*(L.len-180)/31;props.push({x,type:n%5,seed:n*31+i*101})}
npc=i===0?{x:315,y:groundAt(315)-80,name:'Edrin'}:null;
caveDoor=i===0?{x:1270,y:groundAt(1270)-72}:null;
gate=i===0?{x:3310,y:groundAt(3310)-150,open:state.gateOpen}:null;
checkpoint={x:i===0?2250:L.len*.55,lit:spawn>(i===0?2200:L.len*.5)};
secret={x:i===0?1780:L.len*.34,taken:false};
if(i===6){boss={x:3650,y:groundAt(3650)-118,w:64,h:112,hp:600,max:600,state:'idle',timer:90,face:-1,ifr:0,dead:false}}
$('#area').innerHTML='<b>'+(i+1)+' · '+L.name+'</b><small>'+L.sub+'</small>';$('#quest').innerHTML='<b>Objetivo</b> · '+L.quest;openDialog(DIALOGS[i][0],DIALOGS[i][1]);updateHUD();save()}
function enterCave(){areaMode='cave';player.x=180;player.y=caveGround(180)-94;player.vx=0;cam=0;enemies=[makeEnemy(780,3),makeEnemy(1120,0,true),makeEnemy(1480,1)];for(let e of enemies)e.y=caveGround(e.x)-e.h;props=[];for(let n=0;n<18;n++)props.push({x:80+n*110,type:6,seed:n});openDialog('Narrador','A gruta desce sob as raízes do carvalho. Marcas recentes de botas desaparecem na escuridão.')}
function exitCave(){areaMode='world';let x=1290;player=newPlayer(x);cam=clamp(x-W*.32,0,LEVELS[state.level].len-W);buildWorldEnemiesKeep();}
function buildWorldEnemiesKeep(){let L=LEVELS[state.level];enemies=[];for(let n=0;n<11+state.level;n++){let x=520+n*((L.len-900)/(10+state.level));if(Math.abs(x-player.x)>250)enemies.push(makeEnemy(x,(n+state.level)%4,n%6===5))}}
function interact(){if(closeDialog())return;if(areaMode==='cave'){
if(player.x>1670){if(!state.hasSigil){state.hasSigil=true;state.marks+=25;openDialog('Kael','O selo ainda está inteiro. Edrin tinha razão: a guarda não abandonou o portão. Alguém a impediu de voltar.');save()}else exitCave();return}
if(player.x<110){exitCave();return}
}else{
if(npc&&Math.abs(player.x-npc.x)<85){openDialog('Edrin',state.hasSigil?'Você encontrou o selo... então alguns dos nossos chegaram à gruta. Abra o portão. Eu cuidarei dos que ficarem para trás.':DIALOGS[0][1]);return}
if(caveDoor&&Math.abs(player.x-caveDoor.x)<90){enterCave();return}
if(checkpoint&&Math.abs(player.x-checkpoint.x)<80){checkpoint.lit=true;state.checkpoint=checkpoint.x;state.hp=state.maxHp;state.potions=Math.max(state.potions,2);openDialog('Marco de Vigília','A chama responde à espada. Progresso salvo.');save();return}
if(gate&&Math.abs(player.x-gate.x)<110&&!gate.open){if(state.hasSigil){gate.open=true;state.gateOpen=true;openDialog('Kael','O selo encaixa. O mecanismo ainda vive.');save()}else openDialog('Portão Oriental','O encaixe do selo está vazio. A grade não cede.');return}
if(secret&&!secret.taken&&Math.abs(player.x-secret.x)<70){secret.taken=true;state.crystals++;state.maxHp+=8;state.hp=state.maxHp;openDialog('Fragmento Lunar','Um fragmento antigo pulsa sob as raízes. Vitalidade máxima aumentada.');save();return}
}}
function rectHit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function playerAttack(dmg,reach,heavy=false){let hb={x:player.face>0?player.x+24:player.x-reach,y:player.y+8,w:reach,h:68};let hitSomething=false;for(let e of enemies){if(e.dead||e.ifr>0)continue;if(rectHit(hb,e)){if(e.state==='block'&&!heavy){spark(e.x,e.y+30,'#c9c3aa');e.state='recover';e.timer=24;shake=4}else{e.hp-=dmg;e.ifr=14;e.state='hurt';e.timer=18;e.vx=player.face*(heavy?7:4);blood(e.x+e.w/2,e.y+35);shake=heavy?10:6;if(e.hp<=0){e.dead=true;state.marks+=e.elite?12:5;burst(e.x,e.y,'#bba477')}}hitSomething=true}}
if(boss&&!boss.dead&&boss.ifr<=0&&rectHit(hb,boss)){boss.hp-=dmg;boss.ifr=12;boss.state='hurt';boss.timer=18;shake=heavy?12:7;blood(boss.x+30,boss.y+40);if(boss.hp<=0){boss.dead=true;openDialog('Narrador','Vharos cai de joelhos. A coroa quebrada permanece entre vocês, ainda refletindo uma luz que não existe.')}}
if(!hitSomething)whoosh(player.x+player.face*50,player.y+35)}
function hurtPlayer(dmg,from){if(player.ifr>0||player.dodge>0)return;if(player.guard>0&&Math.sign(from-player.x)===player.face){state.st-=Math.min(state.st,dmg*1.1);spark(player.x,player.y+35,'#e0d0a2');if(player.parry>0){for(let e of enemies)if(Math.abs(e.x-player.x)<110){e.state='stunned';e.timer=55;e.vx=-e.face*4}shake=9;return}dmg*=.32}
state.hp-=dmg;player.ifr=44;player.hurt=20;player.vx=Math.sign(player.x-from)*6;shake=9;blood(player.x+18,player.y+32);if(state.hp<=0){state.hp=state.maxHp;state.st=100;state.potions=Math.max(1,state.potions);if(areaMode==='cave'){exitCave()}else{player=newPlayer(state.checkpoint);cam=clamp(player.x-W*.32,0,LEVELS[state.level].len-W)}openDialog('Narrador','Kael cai, mas a chama do último Marco de Vigília o chama de volta.')}}
function updatePlayer(dt){let L=LEVELS[state.level],left=keys.KeyA||keys.ArrowLeft,right=keys.KeyD||keys.ArrowRight,move=(right?1:0)-(left?1:0);if(player.hurt<=0&&player.atk<=0&&player.heavy<=0){if(move){player.vx+=move*.75;player.face=move;player.anim+=Math.abs(player.vx)*.05}else player.anim+=.025;player.vx*=.82;player.vx=clamp(player.vx,-5.4,5.4)}else player.vx*=.92;
if((pressed.Space||pressed.KeyW||pressed.ArrowUp)&&player.onGround&&player.hurt<=0){player.vy=-11.7;player.onGround=false}
if((pressed.ShiftLeft||pressed.ShiftRight)&&state.st>=22&&player.dodge<=0&&player.atk<=0&&player.heavy<=0){player.dodge=20;player.ifr=20;player.vx=player.face*10.5;state.st-=22}
if(pressed.KeyJ&&state.st>=7&&player.atk<=0&&player.heavy<=0&&player.hurt<=0){player.atk=15;player.combo=player.comboT>0?(player.combo%3)+1:1;player.comboT=34;state.st-=7;playerAttack(17+player.combo*3,64,false)}
if(pressed.KeyK&&state.st>=18&&player.atk<=0&&player.heavy<=0&&player.hurt<=0){player.heavy=27;state.st-=18;playerAttack(42,86,true)}
player.guard=(keys.KeyL||keys.KeyQ)?1:0;if(player.guard&&state.st>0&&player.hurt<=0){player.parry=Math.max(player.parry,pressed.KeyL||pressed.KeyQ?8:player.parry-1);player.vx*=.72;state.st-=.08}else player.parry=Math.max(0,player.parry-1);
if(pressed.KeyH&&state.potions>0&&state.hp<state.maxHp){state.potions--;state.hp=Math.min(state.maxHp,state.hp+65);healBurst(player.x,player.y)}
if(pressed.KeyE||pressed.Enter)interact();
state.st=clamp(state.st+.3,0,100);player.vy+=.63;player.x+=player.vx;player.y+=player.vy;let gy=areaMode==='cave'?caveGround(player.x):groundAt(player.x);if(player.y+player.h>=gy){player.y=gy-player.h;player.vy=0;player.onGround=true}else player.onGround=false;
let maxX=areaMode==='cave'?1780:L.len-45;player.x=clamp(player.x,35,maxX);if(player.ifr>0)player.ifr--;if(player.hurt>0)player.hurt--;if(player.atk>0)player.atk--;if(player.heavy>0)player.heavy--;if(player.dodge>0)player.dodge--;if(player.comboT>0)player.comboT--;
if(areaMode==='world'&&gate&&!gate.open&&player.x>gate.x-25)player.x=gate.x-25;
if(areaMode==='world'&&player.x>L.len-85){if(state.level<6){state.gateOpen=false;state.hasSigil=false;buildLevel(state.level+1)}else if(boss&&boss.dead)openDialog('Narrador','A fortaleza abre suas portas para o amanhecer. Fim da build V3.')}
let target=player.x-W*.36,maxCam=(areaMode==='cave'?1780:L.len)-W;cam=lerp(cam,clamp(target,0,Math.max(0,maxCam)),.075)}
function updateEnemy(e){if(e.dead)return;if(e.ifr>0)e.ifr--;e.y=(areaMode==='cave'?caveGround(e.x):groundAt(e.x))-e.h;let dx=player.x-e.x,dist=Math.abs(dx);e.face=dx>=0?1:-1;if(e.state==='hurt'||e.state==='stunned'||e.state==='recover'){e.x+=e.vx;e.vx*=.84;if(--e.timer<=0)e.state='alert';return}
if(e.type===2){if(dist<430)e.state='alert';if(e.state==='alert'){e.vx+=Math.sign(-dx)*.08;e.vx=clamp(e.vx,-1.5,1.5);if(dist>270)e.vx+=Math.sign(dx)*.12;if(dist>180&&dist<420&&e.timer<=0){e.state='shoot';e.timer=34}else e.timer--}if(e.state==='shoot'){e.vx*=.8;if(--e.timer===12){projectiles.push({x:e.x+20,y:e.y+25,vx:e.face*6.8,vy:-.4,w:12,h:4,life:150,type:'arrow'});e.state='recover';e.timer=38}}e.x+=e.vx;return}
if(e.state==='patrol'){e.vx+=Math.sin(time*.001+e.home)*.025;e.vx=clamp(e.vx,-.8,.8);if(dist<260)e.state='alert'}else if(e.state==='alert'){if(dist>90){e.vx+=Math.sign(dx)*(e.type===1?.17:.11);e.vx=clamp(e.vx,-(e.type===1?3.3:2.0),e.type===1?3.3:2.0)}else{e.vx*=.7;e.state=rnd(time+e.x)>.72&&e.type===0?'block':'windup';e.timer=e.state==='block'?28:(e.type===1?18:28)}}else if(e.state==='block'){e.vx*=.7;if(--e.timer<=0)e.state='windup',e.timer=22}else if(e.state==='windup'){e.vx*=.55;if(--e.timer<=0){e.state='attack';e.timer=12}}else if(e.state==='attack'){if(e.timer===12){let hb={x:e.face>0?e.x+e.w-5:e.x-52,y:e.y+12,w:56,h:e.h-16};if(rectHit(hb,player))hurtPlayer(e.type===1?15:e.elite?23:18,e.x)}if(--e.timer<=0)e.state='recover',e.timer=30}
e.x+=e.vx;if(dist>650)e.state='patrol'}
function updateBoss(){if(!boss||boss.dead)return;if(boss.ifr>0)boss.ifr--;boss.y=groundAt(boss.x)-boss.h;let dx=player.x-boss.x,d=Math.abs(dx);boss.face=dx>=0?1:-1;if(boss.state==='hurt'){if(--boss.timer<=0)boss.state='idle';return}if(boss.state==='idle'){if(d>125)boss.x+=Math.sign(dx)*1.8;if(--boss.timer<=0){boss.state=rnd(time)>.55?'dash':'cast';boss.timer=boss.state==='dash'?42:70}}else if(boss.state==='dash'){if(boss.timer>20)boss.x+=boss.face*6.2;if(boss.timer===18&&d<130)hurtPlayer(28,boss.x);if(--boss.timer<=0){boss.state='idle';boss.timer=45}}else if(boss.state==='cast'){if(boss.timer===42)for(let k=-2;k<=2;k++)projectiles.push({x:boss.x+30,y:boss.y+35,vx:boss.face*(4.5+Math.abs(k)*.3),vy:k*1.2,w:14,h:10,life:180,type:'dark'});if(--boss.timer<=0){boss.state='idle';boss.timer=45}}}
function updateProjectiles(){for(let p of projectiles){p.x+=p.vx;p.y+=p.vy;p.life--;if(rectHit(p,player)){hurtPlayer(p.type==='dark'?20:13,p.x);p.life=0}}projectiles=projectiles.filter(p=>p.life>0)}
function updateParticles(){for(let p of particles){p.x+=p.vx;p.y+=p.vy;p.vy+=p.g||.08;p.life--;p.a=p.life/p.max}particles=particles.filter(p=>p.life>0)}
function update(dt){if(scene!=='game'||paused)return;time+=dt;updatePlayer(dt);for(let e of enemies)updateEnemy(e);updateBoss();updateProjectiles();updateParticles();shake*=.82;updateHUD();updatePrompt()}
function burst(x,y,c){for(let i=0;i<16;i++)particles.push({x,y,vx:(rnd(i+time)-.5)*6,vy:(rnd(i*3+time)-.7)*6,g:.14,life:32,max:32,c,a:1})}
function blood(x,y){burst(x,y,'#7d2927')}function spark(x,y,c){burst(x,y,c)}function whoosh(x,y){for(let i=0;i<7;i++)particles.push({x,y:y+i*3,vx:player.face*(2+i*.2),vy:-.3,g:0,life:12,max:12,c:'#d8d4c8',a:1})}function healBurst(x,y){for(let i=0;i<18;i++)particles.push({x:x+(rnd(i)-.5)*30,y:y+50,vx:0,vy:-1-rnd(i+4)*2,g:0,life:38,max:38,c:'#7fb08d',a:1})}
function updateHUD(){$('#hpFill').style.width=(state.hp/state.maxHp*100)+'%';$('#stFill').style.width=state.st+'%';$('#hpText').textContent=Math.ceil(state.hp)+'/'+state.maxHp;$('#potions').textContent=state.potions;$('#marks').textContent=state.marks;$('#sigil').textContent=state.hasSigil?'SIM':'—';if(boss&&!boss.dead){show('#bossHud',true);$('#bossFill').style.width=(boss.hp/boss.max*100)+'%'}else show('#bossHud',false)}
function updatePrompt(){let text='';if(areaMode==='cave'){if(player.x<130)text='E · Voltar à estrada';if(player.x>1640)text=state.hasSigil?'E · Sair da gruta':'E · Pegar Selo do Guardião'}else{if(npc&&Math.abs(player.x-npc.x)<85)text='E · Falar com Edrin';if(caveDoor&&Math.abs(player.x-caveDoor.x)<90)text='E · Entrar na gruta';if(checkpoint&&Math.abs(player.x-checkpoint.x)<80)text='E · Acender Marco de Vigília';if(gate&&Math.abs(player.x-gate.x)<110&&!gate.open)text='E · Examinar portão';if(secret&&!secret.taken&&Math.abs(player.x-secret.x)<70)text='E · Examinar raízes'}$('#prompt').textContent=text;show('#prompt',!!text)}
function skyGradient(a,b){let g=ctx.createLinearGradient(0,0,0,H);g.addColorStop(0,a);g.addColorStop(.72,b);g.addColorStop(1,'#141415');return g}
function drawMountain(offset,base,amp,color,seed){ctx.fillStyle=color;ctx.beginPath();ctx.moveTo(0,H);for(let x=-100;x<=W+150;x+=100){let wx=x+cam*offset;let y=base-Math.abs(Math.sin(wx*.0017+seed))*amp-rnd(Math.floor(wx/100)+seed)*amp*.5;ctx.lineTo(x,y)}ctx.lineTo(W,H);ctx.closePath();ctx.fill()}
function drawTree(wx,seed,front=false){let x=wx-cam*(front?1.06:1),gy=groundAt(wx),scale=.8+rnd(seed)*.65;if(x<-130||x>W+130)return;ctx.save();ctx.translate(x,gy);ctx.scale(scale,scale);ctx.strokeStyle=front?'#171613':'#262722';ctx.lineCap='round';ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(0,6);ctx.quadraticCurveTo(-8,-55,4,-118);ctx.stroke();ctx.lineWidth=8;for(let i=0;i<5;i++){let yy=-45-i*18,dir=i%2?1:-1;ctx.beginPath();ctx.moveTo(dir*2,yy);ctx.quadraticCurveTo(dir*(28+rnd(seed+i)*35),yy-10,dir*(55+rnd(seed+i+9)*25),yy-36);ctx.stroke()}ctx.fillStyle=front?'#22241f':'#343a30';for(let i=0;i<9;i++){let ang=i*2.1+seed,rx=Math.cos(ang)*(42+rnd(i+seed)*38),ry=-105+Math.sin(ang)*(35+rnd(i+2)*28);ctx.beginPath();ctx.ellipse(rx,ry,38+rnd(i+7)*20,22+rnd(i+3)*15,ang*.2,0,Math.PI*2);ctx.fill()}ctx.restore()}
function drawRuin(wx,seed){let x=wx-cam,gy=groundAt(wx);if(x<-220||x>W+220)return;ctx.save();ctx.translate(x,gy);ctx.fillStyle='#45433d';ctx.strokeStyle='#252522';ctx.lineWidth=3;ctx.fillRect(-65,-95,130,95);ctx.fillStyle='#1a1b1b';ctx.beginPath();ctx.arc(0,-48,28,Math.PI,0);ctx.lineTo(28,0);ctx.lineTo(-28,0);ctx.closePath();ctx.fill();ctx.fillStyle='#56534c';for(let i=0;i<6;i++)ctx.fillRect(-62+i*22,-92-rnd(seed+i)*3,18,12);ctx.restore()}
function drawRock(wx,seed,front=false){let x=wx-cam*(front?1.04:1),gy=groundAt(wx);ctx.save();ctx.translate(x,gy);ctx.fillStyle=front?'#242421':'#3d3e39';ctx.beginPath();ctx.moveTo(-25,0);ctx.lineTo(-15,-20-rnd(seed)*20);ctx.lineTo(8,-28-rnd(seed+2)*12);ctx.lineTo(28,-6);ctx.lineTo(22,0);ctx.closePath();ctx.fill();ctx.restore()}
function drawCave(){ctx.fillStyle=skyGradient('#111923','#28303a');ctx.fillRect(0,0,W,H);ctx.fillStyle='#0b0d11';ctx.beginPath();ctx.moveTo(0,0);for(let x=0;x<=W;x+=60)ctx.lineTo(x,70+rnd(Math.floor((x+cam)/60))*80);ctx.lineTo(W,0);ctx.closePath();ctx.fill();ctx.fillStyle='#1c2025';ctx.fillRect(0,caveGround(cam)-5,W,H);for(let i=0;i<18;i++){let wx=i*130-(cam%130),h=30+rnd(i)*85;ctx.fillStyle=i%3?'#2f3946':'#425b72';ctx.beginPath();ctx.moveTo(wx,H-105);ctx.lineTo(wx+18,H-105-h);ctx.lineTo(wx+34,H-105);ctx.fill()}for(let i=0;i<6;i++){let wx=250+i*310-cam*.35;ctx.fillStyle='rgba(93,126,155,.09)';ctx.beginPath();ctx.ellipse(wx,H*.45,190,55,0,0,Math.PI*2);ctx.fill()}drawCaveAltar()}
function drawCaveAltar(){let x=1710-cam;if(x<-200||x>W+200)return;ctx.save();ctx.translate(x,caveGround(1710));ctx.fillStyle='#353a3d';ctx.fillRect(-60,-65,120,65);ctx.fillStyle='#8d7847';ctx.beginPath();ctx.arc(0,-83,18,0,7);ctx.fill();ctx.strokeStyle='#d5bf77';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-104);ctx.lineTo(0,-63);ctx.moveTo(-14,-84);ctx.lineTo(14,-84);ctx.stroke();ctx.restore()}
function drawEnvironment(){let L=LEVELS[state.level];if(areaMode==='cave'){drawCave();return}ctx.fillStyle=skyGradient(L.sky[0],L.sky[1]);ctx.fillRect(0,0,W,H);drawMountain(.08,H*.57,170,'rgba(12,15,18,.42)',1+state.level);drawMountain(.16,H*.66,125,'rgba(18,20,21,.60)',3+state.level);for(let p of props){if(state.level===0){if(p.type===0||p.type===3)drawTree(p.x,p.seed,false);else if(p.type===1)drawRock(p.x,p.seed);else if(p.type===2)drawRuin(p.x,p.seed)}else if(state.level===1||state.level===6){if(p.type%2)drawRuin(p.x,p.seed);else drawRock(p.x,p.seed)}else if(state.level===2){drawRock(p.x,p.seed)}else if(state.level===3){if(p.type%2)drawRuin(p.x,p.seed);else drawTree(p.x,p.seed,false)}else if(state.level===4){drawRuin(p.x,p.seed)}else drawRock(p.x,p.seed)}
ctx.fillStyle=L.ground;ctx.beginPath();ctx.moveTo(-10,H);for(let sx=-20;sx<=W+30;sx+=20){let wx=sx+cam;ctx.lineTo(sx,groundAt(wx))}ctx.lineTo(W+20,H);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(170,170,150,.22)';ctx.lineWidth=2;ctx.beginPath();for(let sx=0;sx<=W;sx+=20){let wx=sx+cam,gy=groundAt(wx);if(sx===0)ctx.moveTo(sx,gy);else ctx.lineTo(sx,gy)}ctx.stroke();
for(let i=0;i<34;i++){let wx=i*117+(state.level*41)%80,x=wx-(cam%3970);if(x>-50&&x<W+50){let gy=groundAt(wx);ctx.strokeStyle=L.accent+'88';ctx.lineWidth=1;for(let k=0;k<5;k++){ctx.beginPath();ctx.moveTo(x+k*3,gy);ctx.lineTo(x-5+k*4,gy-10-rnd(i+k)*11);ctx.stroke()}}}
if(npc)drawNPC(npc);if(caveDoor)drawCaveEntrance(caveDoor);if(checkpoint)drawCheckpoint(checkpoint);if(gate)drawGate(gate);if(secret&&!secret.taken)drawSecret(secret)}
function limb(x1,y1,x2,y2,x3,y3,w,c){ctx.strokeStyle=c;ctx.lineWidth=w;ctx.lineCap='round';ctx.lineJoin='round';ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.lineTo(x3,y3);ctx.stroke()}
function drawKael(){let x=player.x-cam,y=player.y,t=player.anim,run=Math.abs(player.vx)>1&&player.onGround,jump=!player.onGround;ctx.save();ctx.translate(x+20,y+47);ctx.scale(player.face,1);ctx.globalAlpha=player.ifr>0&&Math.floor(player.ifr/3)%2?0.48:1;let stride=run?Math.sin(t*6)*18:0,bob=run?Math.abs(Math.sin(t*6))*3:Math.sin(time*.003)*1.2;if(jump)stride=-8;ctx.translate(0,bob);
ctx.fillStyle='rgba(0,0,0,.36)';ctx.beginPath();ctx.ellipse(0,43,28,7,0,0,7);ctx.fill();
limb(-6,15,-9,32,-14+stride*.35,45,9,'#31363a');limb(7,15,10,31,14-stride*.35,45,9,'#3a3e42');ctx.fillStyle='#1c1f22';ctx.beginPath();ctx.moveTo(-23+stride*.35,43);ctx.lineTo(-7+stride*.35,41);ctx.lineTo(-4+stride*.35,48);ctx.lineTo(-25+stride*.35,49);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(5-stride*.35,41);ctx.lineTo(22-stride*.35,43);ctx.lineTo(25-stride*.35,49);ctx.lineTo(4-stride*.35,48);ctx.closePath();ctx.fill();
ctx.fillStyle='#394148';ctx.beginPath();ctx.moveTo(-13,-18);ctx.quadraticCurveTo(0,-25,13,-18);ctx.lineTo(15,17);ctx.quadraticCurveTo(0,24,-15,17);ctx.closePath();ctx.fill();ctx.fillStyle='#252b30';ctx.beginPath();ctx.moveTo(-14,-13);ctx.lineTo(-24,8);ctx.lineTo(-17,20);ctx.lineTo(-10,7);ctx.closePath();ctx.fill();ctx.fillStyle='#806846';ctx.fillRect(-15,11,30,5);ctx.fillStyle='#a6926a';ctx.fillRect(-2,11,5,5);
let atk=player.atk>0?1-player.atk/15:player.heavy>0?1-player.heavy/27:0,armAng=player.atk>0?lerp(-.7,1.05,Math.sin(atk*Math.PI)):player.heavy>0?lerp(-1.5,.8,Math.sin(atk*Math.PI)):-.25+Math.sin(t*3)*.08;ctx.save();ctx.rotate(armAng);limb(8,-10,20,2,27,16,8,'#3b4146');ctx.fillStyle='#9a7458';ctx.beginPath();ctx.ellipse(28,17,5,6,.2,0,7);ctx.fill();ctx.strokeStyle='#c9c8bf';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(29,18);ctx.lineTo(62,28);ctx.stroke();ctx.strokeStyle='#83734e';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(25,17);ctx.lineTo(34,20);ctx.stroke();ctx.restore();
limb(-9,-10,-20,2,-24,16,8,'#32383d');ctx.fillStyle='#9a7458';ctx.beginPath();ctx.ellipse(-24,17,5,6,0,0,7);ctx.fill();
ctx.fillStyle='#a88466';ctx.beginPath();ctx.moveTo(-10,-31);ctx.quadraticCurveTo(-8,-43,0,-46);ctx.quadraticCurveTo(12,-43,11,-29);ctx.lineTo(6,-20);ctx.quadraticCurveTo(0,-16,-8,-21);ctx.closePath();ctx.fill();ctx.fillStyle='#31271f';ctx.beginPath();ctx.moveTo(-12,-38);ctx.quadraticCurveTo(-6,-50,7,-47);ctx.lineTo(14,-39);ctx.lineTo(8,-34);ctx.lineTo(5,-41);ctx.lineTo(-1,-35);ctx.lineTo(-8,-36);ctx.closePath();ctx.fill();ctx.strokeStyle='#2a211b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(7,-27);ctx.lineTo(12,-25);ctx.stroke();
ctx.strokeStyle='#66533d';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-9,15);ctx.lineTo(-18,32);ctx.stroke();ctx.restore()}
function drawHumanoidEnemy(e){let x=e.x-cam,y=e.y,t=time*.004+e.x*.01;ctx.save();ctx.translate(x+e.w/2,y+e.h*.53);ctx.scale(e.face,1);let stride=e.state==='alert'?Math.sin(t*7)*12:Math.sin(t*2)*4,col=e.elite?'#5d4b42':'#44484a';ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,e.h*.45,24,6,0,0,7);ctx.fill();limb(-5,12,-8,29,-12+stride*.35,42,8,'#2d3032');limb(6,12,9,29,13-stride*.35,42,8,'#343739');ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(-14,-18);ctx.lineTo(13,-18);ctx.lineTo(16,18);ctx.lineTo(-16,18);ctx.closePath();ctx.fill();ctx.fillStyle=e.elite?'#8d704c':'#655a4b';ctx.fillRect(-15,9,31,5);let a=e.state==='windup'?-1.15:e.state==='attack'?.65:-.15;ctx.save();ctx.rotate(a);limb(8,-9,20,2,26,14,8,col);ctx.strokeStyle='#b8b7ad';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(27,14);ctx.lineTo(54,23);ctx.stroke();ctx.restore();limb(-8,-9,-19,1,-22,13,8,col);ctx.fillStyle='#8d6f5c';ctx.beginPath();ctx.moveTo(-10,-30);ctx.quadraticCurveTo(-8,-42,0,-45);ctx.quadraticCurveTo(10,-42,10,-30);ctx.lineTo(5,-21);ctx.lineTo(-7,-22);ctx.closePath();ctx.fill();ctx.fillStyle='#2d2c2b';ctx.beginPath();ctx.moveTo(-12,-39);ctx.lineTo(0,-48);ctx.lineTo(13,-39);ctx.lineTo(9,-33);ctx.lineTo(-9,-33);ctx.closePath();ctx.fill();if(e.state==='block'){ctx.fillStyle='#4e5558';ctx.beginPath();ctx.ellipse(22,-1,11,19,0,0,7);ctx.fill();ctx.strokeStyle='#797e80';ctx.stroke()}ctx.restore()}
function drawWolf(e){let x=e.x-cam,y=e.y;ctx.save();ctx.translate(x+26,y+30);ctx.scale(e.face,1);let run=Math.sin(time*.012+e.x)*8;ctx.fillStyle='rgba(0,0,0,.35)';ctx.beginPath();ctx.ellipse(0,24,30,6,0,0,7);ctx.fill();ctx.fillStyle='#514a42';ctx.beginPath();ctx.ellipse(-2,0,26,15,-.1,0,7);ctx.fill();ctx.beginPath();ctx.moveTo(18,-7);ctx.lineTo(36,-16);ctx.lineTo(38,1);ctx.lineTo(22,8);ctx.closePath();ctx.fill();ctx.fillStyle='#2e2b29';ctx.beginPath();ctx.moveTo(25,-15);ctx.lineTo(27,-28);ctx.lineTo(34,-18);ctx.closePath();ctx.fill();ctx.beginPath();ctx.moveTo(34,-16);ctx.lineTo(40,-28);ctx.lineTo(42,-12);ctx.closePath();ctx.fill();limb(-12,8,-13,18,-17+run*.3,25,6,'#433e39');limb(8,8,10,18,14-run*.3,25,6,'#433e39');ctx.strokeStyle='#423b35';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(-24,-3);ctx.quadraticCurveTo(-42,-15,-48,-3);ctx.stroke();ctx.fillStyle='#bb8b59';ctx.beginPath();ctx.arc(36,-6,2.2,0,7);ctx.fill();ctx.restore()}
function drawArcher(e){drawHumanoidEnemy(e);let x=e.x-cam+e.w/2,y=e.y+e.h*.53;ctx.save();ctx.translate(x,y);ctx.scale(e.face,1);ctx.strokeStyle='#7c6848';ctx.lineWidth=3;ctx.beginPath();ctx.arc(22,-2,18,-1.2,1.2);ctx.stroke();ctx.restore()}
function drawWraith(e){let x=e.x-cam,y=e.y,hover=Math.sin(time*.006+e.x)*7;ctx.save();ctx.translate(x+20,y+38+hover);ctx.globalAlpha=.78;ctx.fillStyle='rgba(101,117,132,.62)';ctx.beginPath();ctx.moveTo(-18,-20);ctx.quadraticCurveTo(0,-38,18,-20);ctx.lineTo(24,25);ctx.lineTo(10,18);ctx.lineTo(0,29);ctx.lineTo(-9,19);ctx.lineTo(-22,25);ctx.closePath();ctx.fill();ctx.fillStyle='#151a20';ctx.beginPath();ctx.ellipse(0,-17,9,12,0,0,7);ctx.fill();ctx.fillStyle='#87a5b5';ctx.fillRect(-5,-20,3,2);ctx.fillRect(3,-20,3,2);ctx.restore()}
function drawNPC(n){let fake={...n,w:40,h:80,face:1,state:'idle',elite:false};drawHumanoidEnemy(fake)}
function drawGate(g){let x=g.x-cam,gy=groundAt(g.x);ctx.save();ctx.translate(x,gy);ctx.fillStyle='#484742';ctx.fillRect(-42,-160,34,160);ctx.fillRect(70,-160,34,160);ctx.fillRect(-48,-165,158,26);ctx.fillStyle='#2b2b2a';ctx.fillRect(-8,-138,78,138);if(!g.open){ctx.strokeStyle='#77736b';ctx.lineWidth=6;for(let i=0;i<6;i++){ctx.beginPath();ctx.moveTo(i*15-5,-138);ctx.lineTo(i*15-5,0);ctx.stroke()}ctx.strokeStyle='#8c7442';ctx.beginPath();ctx.arc(31,-72,12,0,7);ctx.stroke()}else{ctx.fillStyle='#090a0b';ctx.fillRect(-8,-138,78,138)}ctx.restore()}
function drawCaveEntrance(c){let x=c.x-cam,gy=groundAt(c.x);ctx.save();ctx.translate(x,gy);ctx.fillStyle='#292a27';ctx.beginPath();ctx.moveTo(-62,0);ctx.lineTo(-46,-72);ctx.quadraticCurveTo(0,-112,50,-72);ctx.lineTo(68,0);ctx.closePath();ctx.fill();ctx.fillStyle='#090b0d';ctx.beginPath();ctx.moveTo(-28,0);ctx.lineTo(-23,-53);ctx.quadraticCurveTo(0,-77,27,-52);ctx.lineTo(32,0);ctx.closePath();ctx.fill();ctx.restore()}
function drawCheckpoint(c){let x=c.x-cam,gy=groundAt(c.x);ctx.save();ctx.translate(x,gy);ctx.strokeStyle='#4b4b47';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(0,-50);ctx.stroke();ctx.fillStyle=c.lit?'#d7a859':'#403c33';ctx.beginPath();ctx.moveTo(-8,-52);ctx.quadraticCurveTo(0,-80,8,-52);ctx.quadraticCurveTo(0,-42,-8,-52);ctx.fill();if(c.lit){ctx.fillStyle='rgba(224,172,82,.11)';ctx.beginPath();ctx.arc(0,-54,42,0,7);ctx.fill()}ctx.restore()}
function drawSecret(s){let x=s.x-cam,gy=groundAt(s.x);ctx.save();ctx.translate(x,gy);ctx.fillStyle='rgba(117,153,183,.24)';ctx.beginPath();ctx.arc(0,-12,22,0,7);ctx.fill();ctx.fillStyle='#7fa3bd';ctx.beginPath();ctx.moveTo(0,-38);ctx.lineTo(11,-14);ctx.lineTo(0,0);ctx.lineTo(-10,-14);ctx.closePath();ctx.fill();ctx.restore()}
function drawBoss(){if(!boss||boss.dead)return;let x=boss.x-cam,y=boss.y;ctx.save();ctx.translate(x+32,y+57);ctx.scale(boss.face,1);ctx.fillStyle='rgba(0,0,0,.45)';ctx.beginPath();ctx.ellipse(0,55,38,8,0,0,7);ctx.fill();limb(-9,18,-13,39,-18,55,12,'#252429');limb(10,18,14,39,19,55,12,'#2d2c31');ctx.fillStyle='#393139';ctx.beginPath();ctx.moveTo(-22,-30);ctx.lineTo(20,-30);ctx.lineTo(27,23);ctx.lineTo(-26,23);ctx.closePath();ctx.fill();ctx.fillStyle='#6f434b';ctx.fillRect(-25,10,52,7);ctx.fillStyle='#5b5a5e';ctx.beginPath();ctx.moveTo(-26,-24);ctx.lineTo(-37,-10);ctx.lineTo(-27,2);ctx.closePath();ctx.fill();let a=boss.state==='dash'?.8:boss.state==='cast'?-1.1:-.2;ctx.save();ctx.rotate(a);limb(12,-20,27,-3,34,15,11,'#36343a');ctx.strokeStyle='#d0c7b1';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(34,15);ctx.lineTo(78,28);ctx.stroke();ctx.restore();ctx.fillStyle='#8e6d60';ctx.beginPath();ctx.moveTo(-14,-47);ctx.quadraticCurveTo(-11,-65,1,-68);ctx.quadraticCurveTo(16,-64,14,-46);ctx.lineTo(7,-34);ctx.lineTo(-9,-35);ctx.closePath();ctx.fill();ctx.fillStyle='#222127';ctx.beginPath();ctx.moveTo(-17,-61);ctx.lineTo(0,-75);ctx.lineTo(18,-60);ctx.lineTo(10,-51);ctx.lineTo(-12,-51);ctx.closePath();ctx.fill();ctx.fillStyle='#b84750';ctx.fillRect(4,-52,3,3);ctx.restore()}
function drawActors(){for(let e of enemies){if(e.dead)continue;if(e.type===0)drawHumanoidEnemy(e);else if(e.type===1)drawWolf(e);else if(e.type===2)drawArcher(e);else drawWraith(e)}drawBoss();drawKael();for(let p of projectiles){ctx.save();ctx.translate(p.x-cam,p.y);ctx.fillStyle=p.type==='dark'?'#8d3950':'#b8aa88';ctx.fillRect(-6,-2,12,4);ctx.restore()}for(let p of particles){ctx.globalAlpha=p.a;ctx.fillStyle=p.c;ctx.fillRect(p.x-cam,p.y,3,3)}ctx.globalAlpha=1}
function drawForeground(){if(areaMode==='cave')return;for(let i=0;i<12;i++){let wx=i*380+160,x=wx-cam*1.05;if(x>-140&&x<W+140){if(i%2===0)drawTree(wx,i+77,true);else drawRock(wx,i+31,true)}}}
function draw(){if(scene!=='game')return;ctx.save();ctx.translate((rnd(time)-.5)*shake,(rnd(time+1)-.5)*shake);drawEnvironment();drawActors();drawForeground();ctx.restore()}
function loop(ts){let dt=Math.min(32,ts-last||16);last=ts;update(dt);draw();pressed={};requestAnimationFrame(loop)}requestAnimationFrame(loop);
function togglePause(){if(!$('#dialog').classList.contains('hidden'))return;paused=!paused;show('#pause',paused);if(paused)$('#pauseArea').textContent=LEVELS[state.level].name}
function startGame(i=0){enterGame();paused=false;show('#pause',false);buildLevel(i)}
$('#newGame').onclick=()=>{state={hp:140,maxHp:140,st:100,potions:3,marks:0,keys:0,crystals:0,level:0,checkpoint:110,hasSigil:false,caveSeen:false,gateOpen:false,save:false};startGame(0)};
$('#continueGame').onclick=()=>{load();startGame(state.level||0);player.x=state.checkpoint||110};
$('#controlsBtn').onclick=()=>show('#overlay',true);$('#overlayClose').onclick=()=>show('#overlay',false);$('#resume').onclick=togglePause;$('#toMenu').onclick=()=>{paused=false;scene='menu';show('#pause',false);show('#play',false);show('#menu',true)};
$('#chapterBtn').onclick=()=>{let html='<div class="controls">'+LEVELS.map((l,i)=>'<button class="btn chapter" data-i="'+i+'">'+(i+1)+'. '+l.name+'</button>').join('')+'</div>';$('#overlayTitle').textContent='Seleção de capítulo';$('#overlayBody').innerHTML=html;show('#overlay',true);document.querySelectorAll('.chapter').forEach(b=>b.onclick=()=>{show('#overlay',false);startGame(+b.dataset.i)})};
load();$('#continueGame').disabled=!state.save;updateHUD();
})();